version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=unai
      - MONGO_INITDB_ROOT_PASSWORD=011110
